include $(BUILD_INITIALIZE)

CFLAGS_LOCAL := -std=c99

LOCAL_HEADERS := $(wildcard *.h)
LOCAL_SOURCES := $(wildcard *.c)
LOCAL_STATIC_DEPENDENCIES := 
LOCAL_MODULE := libvector.a

include $(BUILD_STATIC_LIBRARY)
